### ISSUE TITLE
Use uuid() instead of Math.random().toString

### ISSUE THREAD

**Issue by jjinendra3** [ShivaBhattacharjee/TrimIt#1]
Using uuid() is generally more reliable for generating unique id compared to Math.random(), which can sometimes produce duplicate values. Replacing Math.random() with uuid() would improve the uniqueness of your id generation. Would you like me to raise a PR for the same?

**Comment by ShivaBhattacharjee** [comment]
Noted will implement uuid and push it with updated docs
